/*
SQLyog Community v13.2.0 (64 bit)
MySQL - 10.9.3-MariaDB : Database - ecommerce
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`ecommerce` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `ecommerce`;

/*Data for the table `items` */

insert  into `items`(`id`,`sku`,`name`,`display_price`,`quantity`,`general_description`,`created_at`,`updated_at`) values 
(1,'N.384','Kalung Perak 925 Koleksi Aeon Permata Iolite',775000,0,'Koleksi Terbaru dari Sunaka Jewelry dinamakan Koleksi Aeon yang berasal dari bahasa Yunani yang artinya Eternity atau keabadian. \r\nKoleksi ini dihiasi batu  permata Iolite. yaitu batu permata berwarna Biru keunguan (Violetish Blue) dan kata iolite sendiri berasal dari bahasa Yunani yang artinya Violet.\r\n\r\nDipercaya bahwa batu permata iolite membantu meningkatkan pikiran positif, intuisi dan penerimaan diri. Iolite juga dikatakan sangat cocok dengan orang yang memiliki  zodiak Libra, Sagitarius dan Taurus.\r\n\r\nDETAIL PRODUK:\r\nKode : N.384\r\nPanjang Rantai : 45cm (18 IN)\r\nBerat : +- 8 Gram\r\nBahan: Perak 925\r\nWarna:  Rhodium \r\nPermata: Iolite & White Zircon ',NULL,NULL),
(2,'R.716','Cincin Perak 925 Koleksi Aeon Permata Iolite',475000,1,'Koleksi Terbaru dari Sunaka Jewelry dinamakan Koleksi Aeon yang berasal dari bahasa Yunani yang artinya Eternity atau keabadian. \r\nKoleksi ini dihiasi batu  permata Iolite. yaitu batu permata berwarna Biru keunguan (Violetish Blue) dan kata iolite sendiri berasal dari bahasa Yunani yang artinya Violet.\r\n\r\nDipercaya bahwa batu permata iolite membantu meningkatkan pikiran positif, intuisi dan penerimaan diri. Iolite juga dikatakan sangat cocok dengan orang yang memiliki  zodiak Libra, Sagitarius dan Taurus.\r\n\r\nDETAIL PRODUK:\r\nKode : R.716\r\nSize : 5,6,7,8,\r\nBerat : +- 5 Gram\r\nBahan: Perak 925\r\nWarna: i Rhodium \r\nPermata: Iolite & White Zircon ',NULL,NULL),
(3,'E.1283','Anting Perak 925 Koleksi Aeon Permata Iolite',1125000,1,'Koleksi Terbaru dari Sunaka Jewelry dinamakan Koleksi Aeon yang berasal dari bahasa Yunani yang artinya Eternity atau keabadian. \r\nKoleksi ini dihiasi batu  permata Iolite. yaitu batu permata berwarna Biru keunguan (Violetish Blue) dan kata iolite sendiri berasal dari bahasa Yunani yang artinya Violet.\r\n\r\nDipercaya bahwa batu permata iolite membantu meningkatkan pikiran positif, intuisi dan penerimaan diri. Iolite juga dikatakan sangat cocok dengan orang yang memiliki  zodiak Libra, Sagitarius dan Taurus.\r\n\r\nDETAIL PRODUK:\r\nKode : E.1283\r\nPanjang : 7 cm\r\nBerat : +- 16 Gram\r\nBahan: Perak 925\r\nWarna: Rhodium\r\nPermata: Iolite & White Zircon ',NULL,NULL),
(4,'BO.081','Bross Perak 925 Koleksi Aeon Permata Iolite',600000,1,'Koleksi Terbaru dari Sunaka Jewelry dinamakan Koleksi Aeon yang berasal dari bahasa Yunani yang artinya Eternity atau keabadian. \r\nKoleksi ini dihiasi batu  permata Iolite yaitu batu permata berwarna Biru keunguan (Violetish Blue) dan kata iolite sendiri berasal dari bahasa Yunani yang artinya Violet.\r\n\r\nDipercaya bahwa batu permata iolite membantu meningkatkan pikiran positif, intuisi dan penerimaan diri. Iolite juga dikatakan sangat cocok dengan orang yang memiliki  zodiak Libra, Sagitarius dan Taurus.\r\n\r\nDETAIL PRODUK:\r\nKode : BO.081\r\nBerat : +- 8 Gram\r\nBahan: Perak 925\r\nWarna: Rhodium\r\nPermata: Iolite & White Zircon \r\n\r\n',NULL,NULL),
(5,'E.1278','Anting Long Drop Perak 925 Koleksi Aeon Permata Iolite',1200000,1,'Koleksi Terbaru dari Sunaka Jewelry dinamakan Koleksi Aeon yang berasal dari bahasa Yunani yang artinya Eternity atau keabadian. \r\nKoleksi ini dihiasi batu  permata Iolite. yaitu batu permata berwarna Biru keunguan (Violetish Blue) dan kata iolite sendiri berasal dari bahasa Yunani yang artinya Violet.\r\n\r\nDipercaya bahwa batu permata iolite membantu meningkatkan pikiran positif, intuisi dan penerimaan diri. Iolite juga dikatakan sangat cocok dengan orang yang memiliki  zodiak Libra, Sagitarius dan Taurus.\r\n\r\nDETAIL PRODUK:\r\nKode : E.1278\r\nPanjang : +- 5 cm\r\nBerat : +- 7.8 Gram\r\nBahan: Perak 925\r\nWarna: Kombinasi Rhodium \r\nPermata: Iolite & White Zircon',NULL,NULL),
(6,'E.1111','Anting Earcuff Perak 925 Koleksi Aeon Permata Iolite',675000,1,'Koleksi Terbaru dari Sunaka Jewelry dinamakan Koleksi Aeon yang berasal dari bahasa Yunani yang artinya Eternity atau keabadian. \r\nKoleksi ini dihiasi batu  permata Iolite. yaitu batu permata berwarna Biru keunguan (Violetish Blue) dan kata iolite sendiri berasal dari bahasa Yunani yang artinya Violet.\r\n\r\nDipercaya bahwa batu permata iolite membantu meningkatkan pikiran positif, intuisi dan penerimaan diri. Iolite juga dikatakan sangat cocok dengan orang yang memiliki  zodiak Libra, Sagitarius dan Taurus.\r\n\r\nDETAIL PRODUK:\r\nKode : E.1111\r\nPanjang : +- 5 cm\r\nBerat : +- 4,2 Gram\r\nBahan: Perak 925\r\nWarna: Rhodium \r\nPermata: Iolit & White Zircon ',NULL,NULL),
(7,'E.1196','Anting Statement Perak 925 Koleksi Aeon Permata Iolite',1525000,1,'Koleksi Terbaru dari Sunaka Jewelry dinamakan Koleksi Aeon yang berasal dari bahasa Yunani yang artinya Eternity atau keabadian. \r\nKoleksi ini dihiasi batu  permata Iolite. yaitu batu permata berwarna Biru keunguan (Violetish Blue) dan kata iolite sendiri berasal dari bahasa Yunani yang artinya Violet.\r\n\r\nDipercaya bahwa batu permata iolite membantu meningkatkan pikiran positif, intuisi dan penerimaan diri. Iolite juga dikatakan sangat cocok dengan orang yang memiliki  zodiak Libra, Sagitarius dan Taurus.\r\n\r\nDETAIL PRODUK:\r\nKode : E.1196\r\nPanjang : 7 cm\r\nBerat : +- 16,2 Gram\r\nBahan: Perak 925\r\nWarna: Rhodium \r\nPermata: Iolite& White Zircon ',NULL,NULL),
(8,'E.1109','Anting Drop Perak 925 Koleksi Aeon Permata Iolite',925000,1,'Koleksi Terbaru dari Sunaka Jewelry dinamakan Koleksi Aeon yang berasal dari bahasa Yunani yang artinya Eternity atau keabadian. \r\nKoleksi ini dihiasi batu  permata Iolite. yaitu batu permata berwarna Biru keunguan (Violetish Blue) dan kata iolite sendiri berasal dari bahasa Yunani yang artinya Violet.\r\n\r\nDipercaya bahwa batu permata iolite membantu meningkatkan pikiran positif, intuisi dan penerimaan diri. Iolite juga dikatakan sangat cocok dengan orang yang memiliki  zodiak Libra, Sagitarius dan Taurus.\r\n\r\nDETAIL PRODUK:\r\nKode : E.1109\r\nPanjang : 8,5 cm\r\nBerat : +- 9,7 Gram\r\nBahan: Perak 925\r\nWarna: Rhodium\r\nPermata: Iolite & White Zircon ',NULL,NULL),
(9,'R.726','Cincin Perak 925 Koleksi Aeon Permata Iolite',1025000,1,'Koleksi Terbaru dari Sunaka Jewelry dinamakan Koleksi Aeon yang berasal dari bahasa Yunani yang artinya Eternity atau keabadian. \r\nKoleksi ini dihiasi batu  permata Iolite. yaitu batu permata berwarna Biru keunguan (Violetish Blue) dan kata iolite sendiri berasal dari bahasa Yunani yang artinya Violet.\r\n\r\nDipercaya bahwa batu permata iolite membantu meningkatkan pikiran positif, intuisi dan penerimaan diri. Iolite juga dikatakan sangat cocok dengan orang yang memiliki  zodiak Libra, Sagitarius dan Taurus.\r\n\r\nDETAIL PRODUK:\r\nKode : R.726\r\nSize : 5,6,7,8,9\r\nBerat : +- 18.98 Gram\r\nBahan: Perak 925\r\nWarna: i Rhodium \r\nPermata: Iolite & White Zircon \r\n\r\n',NULL,NULL),
(10,'B.786 - B.787','Gelang Bangle Perak 925 Koleksi Aeon Permata Iolite',2175000,1,'Koleksi Terbaru dari Sunaka Jewelry dinamakan Koleksi Aeon yang berasal dari bahasa Yunani yang artinya Eternity atau keabadian. \r\nKoleksi ini dihiasi batu  permata Iolite. yaitu batu permata berwarna Biru keunguan (Violetish Blue) dan kata iolite sendiri berasal dari bahasa Yunani yang artinya Violet.\r\n\r\nDipercaya bahwa batu permata iolite membantu meningkatkan pikiran positif, intuisi dan penerimaan diri. Iolite juga dikatakan sangat cocok dengan orang yang memiliki  zodiak Libra, Sagitarius dan Taurus.\r\n\r\nDETAIL PRODUK:\r\nKode : B.786 - B.787\r\nBerat : +- 20 Gram\r\nBahan: Perak 925\r\nWarna:  Rhodium \r\nPermata: Iolite& White Zircon ',NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
